### ISSUE TITLE
Very nice work.

### ISSUE THREAD

**Issue by gatorback** [adinandradrs/hackintosh-opencore-efi-hp-elitebook-830-g7#1]
Based on your work, I bought an 830-G7 touch.   

Your good work indicates to _DISABLE_  BIOS settings :

1)  Fast Boot
2) Secure Boot
3) Intel Platform Trust
4)Disable TPM in Security

I did find:  

BIOS MAIN MENU->**Security -> TPM Embedded Security  => TPM Device** = hidden.  

**QUESTION 1)** Is this item 3) or 4)?

**QUESTION 2)** Where is the final (3rd / 4th) BIOS setting found?

I understand that the SSD must be in AHCI and not RAID.  **QUESTION 3)** How / where did you set AHCI in the BIOS?

Fun fact:  if you swap out the Intel wifi for Broadcom Wifi, then it is possible to enable Airdrop.

I look forward to your response.  Thank you

**Comment by adinandradrs** [comment]
> Based on your work, I bought an 830-G7 touch.
> 
> Your good work indicates to _DISABLE_ BIOS settings :
> 
> 1. Fast Boot
> 2. Secure Boot
> 3. Intel Platform Trust
>    4)Disable TPM in Security
> 
> I did find:
> 
> BIOS MAIN MENU->**Security -> TPM Embedded Security => TPM Device** = hidden.
> 
> **QUESTION 1)** Is this item 3) or 4)?
> 
> **QUESTION 2)** Where is the final (3rd / 4th) BIOS setting found?
> 
> I understand that the SSD must be in AHCI and not RAID. **QUESTION 3)** How / where did you set AHCI in the BIOS?
> 
> Fun fact: if you swap out the Intel wifi for Broadcom Wifi, then it is possible to enable Airdrop.
> 
> I look forward to your response. Thank you

Hi @gatorback I have updated the BIOS setting as you found (thank you) it was my mistake that 3rd step is equal to 4th step actually, so I just removed the 3rd step and need only to set TPM = hidden.

For the SSD setup, I do not change anything and went through with the factory default.

Thank you

**Comment by gatorback** [comment]
Thank you for the clarification.   It sounds like that you did not change AHCI for the SSD.

BTW, I think you can change the DVMT to 64 MB in the BIOS  to enable external 4K resolution.  Have you had success with an external 4K monitor?

I thought it would please you to know that I modded your work remove the Intel Wifi / BT kexts and installed a natively supported Broadcom WiFI / BT M.2 device.  Airdrop works with Broadcom.

**Comment by Yuki-Judai** [comment]
> > Based on your work, I bought an 830-G7 touch.
> > Your good work indicates to _DISABLE_ BIOS settings :
> > 
> > 1. Fast Boot
> > 2. Secure Boot
> > 3. Intel Platform Trust
> >    4)Disable TPM in Security
> > 
> > I did find:
> > BIOS MAIN MENU->**Security -> TPM Embedded Security => TPM Device** = hidden.
> > **QUESTION 1)** Is this item 3) or 4)?
> > **QUESTION 2)** Where is the final (3rd / 4th) BIOS setting found?
> > I understand that the SSD must be in AHCI and not RAID. **QUESTION 3)** How / where did you set AHCI in the BIOS?
> > Fun fact: if you swap out the Intel wifi for Broadcom Wifi, then it is possible to enable Airdrop.
> > I look forward to your response. Thank you
> 
> Hi @gatorback I have updated the BIOS setting as you found (thank you) it was my mistake that 3rd step is equal to 4th step actually, so I just removed the 3rd step and need only to set TPM = hidden.
> 
> For the SSD setup, I do not change anything and went through with the factory default.
> 
> Thank you

Hi, could you disable CFG Lock in Bios? or disable it in another way? like CFGLock.efi ......

**Comment by adinandradrs** [comment]
> Thank you for the clarification. It sounds like that you did not change AHCI for the SSD.
> 
> BTW, I think you can change the DVMT to 64 MB in the BIOS to enable external 4K resolution. Have you had success with an external 4K monitor?
> 
> I thought it would please you to know that I modded your work remove the Intel Wifi / BT kexts and installed a natively supported Broadcom WiFI / BT M.2 device. Airdrop works with Broadcom.

Sorry for my late reply, yes I didn't change AHCI for the SSD. For the DVMT I found that it has been set as 64 MB but I don't have any external 4k monitor right now to test, I will test it later

That's glad to hear that you have a working airdrop using BCM, I'd like to find it on Ali next month. great work @gatorback

**Comment by gatorback** [comment]
It is my understanding that with 64MB DVMT, 4K is unleashed
